"""Re-create role column

Revision ID: 29f6b6071791
Revises: 48eb359cad2a
Create Date: 2025-06-07 12:13:11.275466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f6b6071791'
down_revision: Union[str, None] = '48eb359cad2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('AUTHENTICATED', 'CLIENT_FREEMIUM', 'CLIENT_PAID', 'STAFF_COLLABORATOR', 'STAFF_MANAGER', 'STAFF_CEO', 'ADMIN', name='userrole'), server_default=sa.text("'authenticated'::userrole"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
