"""Temporarily drop role column

Revision ID: 48eb359cad2a
Revises: e8b9687147f0
Create Date: 2025-06-07 12:11:30.903619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48eb359cad2a'
down_revision: Union[str, None] = 'e8b9687147f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('CLIENT_FREEMIUM', 'CLIENT_PAID', 'STAFF_COLLABORATOR', 'STAFF_MANAGER', 'STAFF_CEO', 'ADMIN', 'authenticated', name='userrole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
