"""Create declaration_requests table and add relationships

Revision ID: 8b1f8d1372a2
Revises: ff11e182b033
Create Date: 2025-07-01 10:42:30.842944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1f8d1372a2'
down_revision: Union[str, None] = 'ff11e182b033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaration_requests',
    sa.Column('yape_plin_transaction_id', sa.Integer(), nullable=True),
    sa.Column('client_profile_id', sa.Integer(), nullable=False),
    sa.Column('service_contract_id', sa.Integer(), nullable=True),
    sa.Column('tax_period', sa.String(length=7), nullable=False),
    sa.Column('declaration_type', postgresql.ENUM('ORIGINAL', 'SUBSTITUTORY', 'RECTIFICATORY', name='declarationtype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_ASSIGNMENT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', name='declarationrequeststatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_contract_id'], ['service_contracts.id'], ),
    sa.ForeignKeyConstraint(['yape_plin_transaction_id'], ['yape_plin_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_requests_client_profile_id'), 'declaration_requests', ['client_profile_id'], unique=False)
    op.create_index(op.f('ix_declaration_requests_id'), 'declaration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_declaration_requests_service_contract_id'), 'declaration_requests', ['service_contract_id'], unique=True)
    op.create_index(op.f('ix_declaration_requests_tax_period'), 'declaration_requests', ['tax_period'], unique=False)
    op.create_index(op.f('ix_declaration_requests_yape_plin_transaction_id'), 'declaration_requests', ['yape_plin_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declaration_requests_yape_plin_transaction_id'), table_name='declaration_requests')
    op.drop_index(op.f('ix_declaration_requests_tax_period'), table_name='declaration_requests')
    op.drop_index(op.f('ix_declaration_requests_service_contract_id'), table_name='declaration_requests')
    op.drop_index(op.f('ix_declaration_requests_id'), table_name='declaration_requests')
    op.drop_index(op.f('ix_declaration_requests_client_profile_id'), table_name='declaration_requests')
    op.drop_table('declaration_requests')
    
    # --- INICIO DE LA CORRECCIÓN EN DOWNGRADE ---
    # El nuevo ENUM 'declarationrequeststatus' se borra automáticamente con la tabla.
    # Le decimos explícitamente que NO borre 'declarationtype' porque es compartido.
    postgresql.ENUM('ORIGINAL', 'SUBSTITUTORY', 'RECTIFICATORY', name='declarationtype', create_type=False).drop(op.get_bind(), checkfirst=False)