"""Add user_declared_amount to yape_plin_transactions

Revision ID: dbdf844f1ffc
Revises: 462cd9a60ff2
Create Date: 2025-06-17 19:40:51.682932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdf844f1ffc'
down_revision: Union[str, None] = '462cd9a60ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yape_plin_transactions', sa.Column('user_declared_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yape_plin_transactions', 'user_declared_amount')
    # ### end Alembic commands ###
