"""Create landing_leads table

Revision ID: fa862148a534
Revises: c48c9aa2f56e
Create Date: 2025-09-05 19:33:50.987046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa862148a534'
down_revision: Union[str, None] = 'c48c9aa2f56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('sol_user', sa.String(), nullable=True),
    sa.Column('encrypted_sol_pass', sa.String(), nullable=True),
    sa.Column('source_landing', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_leads_id'), 'landing_leads', ['id'], unique=False)
    op.create_index(op.f('ix_landing_leads_ruc'), 'landing_leads', ['ruc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_leads_ruc'), table_name='landing_leads')
    op.drop_index(op.f('ix_landing_leads_id'), table_name='landing_leads')
    op.drop_table('landing_leads')
    # ### end Alembic commands ###
