"""Add security_code to fee_payments table

Revision ID: ff11e182b033
Revises: dbdf844f1ffc
Create Date: 2025-06-19 15:30:56.308888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff11e182b033'
down_revision: Union[str, None] = 'dbdf844f1ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_payments', sa.Column('security_code', sa.String(length=3), nullable=True, comment='Optional security code from payment apps like Yape.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_payments', 'security_code')
    # ### end Alembic commands ###
